### ISSUE TITLE
ueberzug error 

### ISSUE THREAD

**Issue by se7en-x230** [slavistan/lf-gadgets#10]
I guess something changed in ueberzug. 
I get `ModuleNotFoundError: No module named 'PIL'`

**Comment by se7en-x230** [comment]
Fixed with 
`pip install Pillow`

**Comment by slavistan** [comment]
@se7en-x230 Sorry for the late reply. Sounds like your ueberzug package (you distro's package manager or pip) is missing a dependency. I'll close this issue as it seems unrelated to this repo but please feel free to reopen if you think otherwise.
