### ISSUE TITLE
paste: no delimiters specified

### ISSUE THREAD

**Issue by bburns-ds** [slavistan/lf-gadgets#14]
Hello, I am trying to run the lf-ueberzug gadget directly just to preview the demo files. The .txt displays, but the other four do not. After I quit I get
`paste: no delimiters specified`
`cleanup:kill:2: kill 22096 failed: no such process`

I'd imagine this is from the 
`cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"`
in lf-ueberzug-previewer, but I don't know why this would be getting no delimiters specified. I am using zsh, but I'm guessing it might just be an OS issue.

I also have no idea what is causing the second line that is returned, so any help there would be welcome as well, assuming it's independent of the first.

**Comment by bburns-ds** [comment]
I tried adding the `\0` delimiter and I still get both messages

**Comment by slavistan** [comment]
Hi @bburns-ds :-) Are you on a GNU/Linux or are you running non-GNU coreutils? Kindly, run `paste --version` in a shell (mine returns `paste (GNU coreutils) 9.0`).

Alternatively, we can remove the whole call to `paste` as its only purpose is to prettify the json input. Try this inside the *lf-ueberzug-previewer*:

```
preview() {
	echo "{\"action\":\"add\",\"identifier\":\"lf-preview\",\"path\":\"$1\",\"x\":$4,\"y\":$5,\"width\":$2,\"height\":$3,\"scaler\":\"contain\"}" > "$LF_UEBERZUG_TEMPDIR/fifo"
}

...
```

**Comment by bburns-ds** [comment]
I get `-- - illegal option` but if I try to install I get `coreutils 9.0_1 is already installed and up-to-date.` :/

**Comment by slavistan** [comment]
Okay, let's keep digging: which linux distribution do you use? And does the alternative `preview` function work? (Just replace it inside *lf-ueberzug-previewer*)

**Comment by bburns-ds** [comment]
Alright sorry I fixed my .zprofile, and GNU paste is working now. If I use either the version of lf-ueberzug-previewer in the repo, or the version you provided above, the files all give a perpetual loading... (including the .txt, which was _somehow_ working before this).

If I quit lf-ueberzug, then I have to ^C twice, and get back `cleanup:kill:2: kill 18xxx failed: no such process`, with the xxx being some three digits.

I am going to keep trying some things on my end to see if this is all a result of me having written bad configs and profiles.
